### ISSUE TITLE
`_get_attr:': undefined method `name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by gpeal** [sxross/MotionModel#40]
I'm getting `'_get_attr:': undefined method`name' for nil:NilClass (NoMethodError)` after upgrading to 0.4.4 and RubyMotion 2.0. The code is here
https://github.com/sxross/MotionModel/blob/master/lib/motion_model/model/model.rb#L624

The closest offending code in my app is

``` ruby
def coordinate
    CLLocationCoordinate2D.new(latitude, longitude) # this line
end
```
